language: python
python:
 - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install swig
install:
  - DEB_HOST_MULTIARCH=x86_64-linux-gnu pip install -I --exists-action=w "git+git://anonscm.debian.org/collab-maint/m2crypto.git@debian/0.21.1-3#egg=M2Crypto"
  - pip install --no-deps MySQL-Python==1.2.5 --use-mirrors
  - pip install --no-deps -r requirements/test.txt --find-links https://pyrepo.addons.mozilla.org/
before_script:
  - mysql -e 'create database solitude;'
  - flake8 . --exclude=./docs/conf.py
script: ./manage.py test --noinput -s
notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
    on_success: change
    on_failure: always
